/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/iphone-12-pro-05dfc991665e45c68c8b7062136c0c6e
Title: iPhone 12 Pro
*/

import { useEffect } from "react";
import * as THREE from "three";
import { Center, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { PUBLIC_PATH } from "../../utilities/constants";

type GLTFResult = GLTF & {
  nodes: {
    iPhone__12_Pro_BodyFrame_0: THREE.Mesh;
    iPhone__12_Pro_MicrophoneSpeaker_0: THREE.Mesh;
    iPhone__12_Pro_GrayGlossy2_0: THREE.Mesh;
    iPhone__12_Pro_Antenna_0: THREE.Mesh;
    iPhone12_Pro_Body_0: THREE.Mesh;
    Camera1_PacificBlue_0: THREE.Mesh;
    Camera1_GrayGlossy_0: THREE.Mesh;
    Camera1_FrontCamera_0: THREE.Mesh;
    Camera1_Blackmatte_0: THREE.Mesh;
    Camera1_Cameralens_0: THREE.Mesh;
    Camera1_Glass_0: THREE.Mesh;
    Flash_Flash2_0: THREE.Mesh;
    Flash_Flash_0: THREE.Mesh;
    LiDar_LiDar__0: THREE.Mesh;
    Bezel_bezel_0: THREE.Mesh;
    FrontCamera_Cameralens_0: THREE.Mesh;
    FrontCamera_FrontCamera_0: THREE.Mesh;
    FrontCamera_Glass_0: THREE.Mesh;
    FrontMic_GrayGlossy2_0: THREE.Mesh;
    FrontMic_MicrophoneSpeaker_0: THREE.Mesh;
    FrontCamera001_bezel001_0: THREE.Mesh;
    Camera3_PacificBlue_0: THREE.Mesh;
    Camera3_GrayGlossy_0: THREE.Mesh;
    Camera3_FrontCamera_0: THREE.Mesh;
    Camera3_Blackmatte_0: THREE.Mesh;
    Camera3_Cameralens_0: THREE.Mesh;
    Camera3_Glass_0: THREE.Mesh;
    Camera2_PacificBlue_0: THREE.Mesh;
    Camera2_GrayGlossy_0: THREE.Mesh;
    Camera2_FrontCamera_0: THREE.Mesh;
    Camera2_Blackmatte_0: THREE.Mesh;
    Camera2_Cameralens_0: THREE.Mesh;
    Camera2_Glass_0: THREE.Mesh;
    Screen_Wallpaper_0: THREE.Mesh;
    Apple_Logo_Logo_0: THREE.Mesh;
    CameraModule001_Glass_0: THREE.Mesh;
    CameraModule002_MicrophoneSpeaker_0: THREE.Mesh;
    VolumeButton_BodyFrame_0: THREE.Mesh;
    PowerButton_BodyFrame_0: THREE.Mesh;
    Port_Blackmatte_0: THREE.Mesh;
    Port_BodyFrame_0: THREE.Mesh;
    SimTray_Blackmatte_0: THREE.Mesh;
    SimTray_BodyFrame_0: THREE.Mesh;
    MuteButton_BodyFrame_0: THREE.Mesh;
  };
  materials: {
    BodyFrame: THREE.MeshStandardMaterial;
    MicrophoneSpeaker: THREE.MeshStandardMaterial;
    GrayGlossy2: THREE.MeshStandardMaterial;
    Antenna: THREE.MeshStandardMaterial;
    Body: THREE.MeshStandardMaterial;
    PacificBlue: THREE.MeshStandardMaterial;
    GrayGlossy: THREE.MeshStandardMaterial;
    FrontCamera: THREE.MeshStandardMaterial;
    Blackmatte: THREE.MeshStandardMaterial;
    Cameralens: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
    Flash2: THREE.MeshStandardMaterial;
    Flash: THREE.MeshStandardMaterial;
    LiDar: THREE.MeshStandardMaterial;
    bezel: THREE.MeshStandardMaterial;
    ["bezel.001"]: THREE.MeshStandardMaterial;
    Wallpaper: THREE.MeshStandardMaterial;
    Logo: THREE.MeshStandardMaterial;
  };
};

type ObjectIphoneProps = JSX.IntrinsicElements["group"] & {
  envMap: THREE.Texture;
  textureSrc: string;
};

const ObjectIphone = (props: ObjectIphoneProps) => {
  const { nodes, materials } = useGLTF(`${PUBLIC_PATH}/objects/iphone/scene.glb`) as GLTFResult;

  useEffect(() => {
    const customTexture = new THREE.TextureLoader().load(props.textureSrc);

    materials.Wallpaper.map = customTexture;
    materials.Wallpaper.metalness = 1;
    materials.Wallpaper.roughness = 0.25;
  }, [materials.Wallpaper, props.textureSrc]);

  useEffect(() => {
    Object.values(materials).forEach((material) => {
      if (material.isMaterial) {
        material.envMap = props.envMap;
        material.needsUpdate = true;
      }
    });
  }, [materials, props.envMap]);

  return (
    <group {...props} dispose={null}>
      <Center>
        <mesh geometry={nodes.iPhone__12_Pro_BodyFrame_0.geometry} material={materials.BodyFrame} />
        <mesh geometry={nodes.iPhone__12_Pro_MicrophoneSpeaker_0.geometry} material={materials.MicrophoneSpeaker} />
        <mesh geometry={nodes.iPhone__12_Pro_GrayGlossy2_0.geometry} material={materials.GrayGlossy2} />
        <mesh geometry={nodes.iPhone__12_Pro_Antenna_0.geometry} material={materials.Antenna} />
        <mesh geometry={nodes.iPhone12_Pro_Body_0.geometry} material={materials.Body} />
        <mesh geometry={nodes.Camera1_PacificBlue_0.geometry} material={materials.PacificBlue} />
        <mesh geometry={nodes.Camera1_GrayGlossy_0.geometry} material={materials.GrayGlossy} />
        <mesh geometry={nodes.Camera1_FrontCamera_0.geometry} material={materials.FrontCamera} />
        <mesh geometry={nodes.Camera1_Blackmatte_0.geometry} material={materials.Blackmatte} />
        <mesh geometry={nodes.Camera1_Cameralens_0.geometry} material={materials.Cameralens} />
        <mesh geometry={nodes.Camera1_Glass_0.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Flash_Flash2_0.geometry} material={materials.Flash2} />
        <mesh geometry={nodes.Flash_Flash_0.geometry} material={materials.Flash} />
        <mesh geometry={nodes.LiDar_LiDar__0.geometry} material={materials.LiDar} />
        <mesh geometry={nodes.Bezel_bezel_0.geometry} material={materials.bezel} />
        <mesh geometry={nodes.FrontCamera_Cameralens_0.geometry} material={materials.Cameralens} />
        <mesh geometry={nodes.FrontCamera_FrontCamera_0.geometry} material={materials.FrontCamera} />
        <mesh geometry={nodes.FrontCamera_Glass_0.geometry} material={materials.Glass} />
        <mesh geometry={nodes.FrontMic_GrayGlossy2_0.geometry} material={materials.GrayGlossy2} />
        <mesh geometry={nodes.FrontMic_MicrophoneSpeaker_0.geometry} material={materials.MicrophoneSpeaker} />
        <mesh geometry={nodes.FrontCamera001_bezel001_0.geometry} material={materials["bezel.001"]} position={[0, 0, -0.001]} />
        <mesh geometry={nodes.Camera3_PacificBlue_0.geometry} material={materials.PacificBlue} />
        <mesh geometry={nodes.Camera3_GrayGlossy_0.geometry} material={materials.GrayGlossy} />
        <mesh geometry={nodes.Camera3_FrontCamera_0.geometry} material={materials.FrontCamera} />
        <mesh geometry={nodes.Camera3_Blackmatte_0.geometry} material={materials.Blackmatte} />
        <mesh geometry={nodes.Camera3_Cameralens_0.geometry} material={materials.Cameralens} />
        <mesh geometry={nodes.Camera3_Glass_0.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Camera2_PacificBlue_0.geometry} material={materials.PacificBlue} />
        <mesh geometry={nodes.Camera2_GrayGlossy_0.geometry} material={materials.GrayGlossy} />
        <mesh geometry={nodes.Camera2_FrontCamera_0.geometry} material={materials.FrontCamera} />
        <mesh geometry={nodes.Camera2_Blackmatte_0.geometry} material={materials.Blackmatte} />
        <mesh geometry={nodes.Camera2_Cameralens_0.geometry} material={materials.Cameralens} />
        <mesh geometry={nodes.Camera2_Glass_0.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Screen_Wallpaper_0.geometry} material={materials.Wallpaper} />
        <mesh geometry={nodes.Apple_Logo_Logo_0.geometry} material={materials.Logo} />
        <mesh geometry={nodes.CameraModule001_Glass_0.geometry} material={materials.Glass} />
        <mesh geometry={nodes.CameraModule002_MicrophoneSpeaker_0.geometry} material={materials.MicrophoneSpeaker} />
        <mesh geometry={nodes.VolumeButton_BodyFrame_0.geometry} material={materials.BodyFrame} />
        <mesh geometry={nodes.PowerButton_BodyFrame_0.geometry} material={materials.BodyFrame} />
        <mesh geometry={nodes.Port_Blackmatte_0.geometry} material={materials.Blackmatte} />
        <mesh geometry={nodes.Port_BodyFrame_0.geometry} material={materials.BodyFrame} />
        <mesh geometry={nodes.SimTray_Blackmatte_0.geometry} material={materials.Blackmatte} />
        <mesh geometry={nodes.SimTray_BodyFrame_0.geometry} material={materials.BodyFrame} />
        <mesh geometry={nodes.MuteButton_BodyFrame_0.geometry} material={materials.BodyFrame} />
      </Center>
    </group>
  );
};

useGLTF.preload(`${PUBLIC_PATH}/objects/iphone/scene.glb`);

export default ObjectIphone;
